centreon/centreon-open-tickets

www/modules/centreon-open-tickets/class/rule.php
Fix the getServiceStateStr and getHostStateStr functions that sometimes return a wrong result.
=> Fix getServiceStateStr and getHostStateStr functions

widgets/open-tickets/src/index.php
=> fix(widgets): Use the last time the service or host is ok

widgets/open-tickets/src/index.php
* User last time ok or up for build ticket url
Refs: #41
=> fix(widget): Fix link to the ticket

widgets/open-tickets/index.php
=> fix(widget): Fix conditional

www/modules/centreon-open-tickets/class/centreonDBManager.class.php, www/modules/centreon-open-tickets/providers/BmcFootprints11/BmcFootprints11Provider.class.php, www/modules/centreon-open-tickets/providers/BmcItsm/BmcItsmProvider.class.php, www/modules/centreon-open-tickets/providers/Easyvista/EasyvistaProvider.class.php, www/modules/centreon-open-tickets/providers/Glpi/GlpiProvider.class.php, www/modules/centreon-open-tickets/providers/Otrs/OtrsProvider.class.php, www/modules/centreon-open-tickets/providers/Serena/SerenaProvider.class.php, www/modules/centreon-open-tickets/providers/ServiceNow/ServiceNowProvider.class.php, www/modules/centreon-open-tickets/providers/Simple/SimpleProvider.class.php
not compatable method with parent AbstractProvider
Resolve CP7M-142 CP7M-143
=> fix(conf): Open tickets > Rule > Add

www/modules/centreon-open-tickets/class/rule.php
when the role didn't select
Resolve CP7M-141
=> fix(cv): open tickets widgets throw exception

www/modules/centreon-open-tickets/class/ticketLog.php, www/modules/centreon-open-tickets/views/logs/ajax/call.php
=> fix(mon): missing DB instance to the live storage of a Ticket Logs

www/modules/centreon-open-tickets/class/centreonDBManager.class.php, www/modules/centreon-open-tickets/providers/Mail/MailProvider.class.php, www/modules/centreon-open-tickets/views/rules/ajax/actions/saveFormConfig.php
=>  fix(widget): open a new ticket

www/modules/centreon-open-tickets/class/rule.php
when added new open ticket widget
Resolve CP7M-141
=> fix(cv): prevent exception with an undefined provider

www/modules/centreon-open-tickets/class/rule.php
Fix the query for displaying the opened ticket into the widget.
=> fix(widget): Bad display on service with macros

www/modules/centreon-open-tickets/providers/Abstract/AbstractProvider.class.php, www/modules/centreon-open-tickets/providers/Abstract/templates/group.ihtml
you'll now be able to have a placeholder in the list when opening a ticket. This is usefull when the ITSM software webservice is using ID instead of readable names.
=> adds a label for custom lists

www/modules/centreon-open-tickets/webServices/rest/centreon_openticket.class.php
it is useless to test the exception message just to throw an exception with the same exception.
=> enh(api) better exception handling

www/modules/centreon-open-tickets/providers/GlpiRestApi/templates/conf_container1extra.ihtml
=> Fix test button

widgets/open-tickets/src/toolbar.php
https://github.com/centreon/centreon/pull/8291
param not use in /widgets/open-tickets/src/action.php
=> fix(security) remove session id parameter

www/modules/centreon-open-tickets/providers/GlpiRestApi/GlpiRestApiProvider.class.php
manage pagination in object lists (20 by 20)
replace #128 
Refs: MON-6258
coauthor : @tanguyvda
=> fix(glpi): manage pagination in object lists

.gitignore, Jenkinsfile, composer.json, composer.lock, ruleset.xml, widgets/open-tickets/index.php, www/modules/centreon-open-tickets/class/request.php
Add requirements to be able to implement githubviolation, sonarQube analysis, coverage and codestyle
**Fixes** # (MON-6423)
linked to : https://github.com/centreon/centreon-build/pull/384
=> enh(chore): add CI requirements for github violation

ruleset.xml, www/modules/centreon-open-tickets/class/request.php, www/modules/centreon-open-tickets/views/rules/index.php
=> fix(chore): enh codingStyle violations

SECURITY.md, ruleset.xml
update security policy GPG key
=> enh(chore): update security policy GPG key

www/modules/centreon-open-tickets/conf.php
=> chore(version): upgrade to 21.04.0

Jenkinsfile, composer.json, widgets/open-tickets/configs.xml, www/modules/centreon-open-tickets/conf.php
=> chore(version): prepare 21.10 serie

widgets/open-tickets/src/index.php
Url from centreon KB is not correct because of the iframe.
=> fix url from Centreon-KB

widgets/open-tickets/configs.xml, widgets/open-tickets/src/export.php, widgets/open-tickets/src/index.php
Jira: IBT-252
allow the use of a disable notif filter for the widget
versions :
=> feat(filters) add disable notif widget filter

www/modules/centreon-open-tickets/providers/GlpiRestApi/templates/conf_container1extra.ihtml, www/modules/centreon-open-tickets/providers/Itop/ItopProvider.class.php, www/modules/centreon-open-tickets/providers/Itop/templates/conf_container1extra.ihtml
fix several php warning/notice
target: master
=> fix(logs): fix some php notices

www/modules/centreon-open-tickets/providers/Mail/MailProvider.class.php
=> fix(provider): fix subject field update of mail provider

Jenkinsfile
missing } to cherry-pick everywhere
=> fix(ci): fixing quality gate pipeline syntax

widgets/open-tickets/src/export.php, www/modules/centreon-open-tickets/providers/Mail/library/class.phpmailer.php
this PR intends to make open-tickets compatible with PHP 7.4
=> enh(codebase): PHP 7.4 Compatibility for 20.10.x (#74)

widgets/open-tickets/src/export.php, www/modules/centreon-open-tickets/providers/Mail/library/class.phpmailer.php
this PR intends to make open-tickets compatible with PHP 7.4
=> enh(codebase): PHP 7.4 Compatibility for 21.04.x

.github/PULL_REQUEST_TEMPLATE.md, Jenkinsfile, composer.json, widgets/open-tickets/configs.xml, www/modules/centreon-open-tickets/conf.php
=> chore(version): prepare 22.04 serie

www/modules/centreon-open-tickets/conf.php
Update version to 20.10.3 in files.
=> chore(install): update version to 20.10.3

www/modules/centreon-open-tickets/conf.php
Update version to 21.04.2 in files.
=> chore(install): update version to 21.04.2

widgets/open-tickets/configs.xml
update widget version to 21.04.2
=> chore(install): update widget version to 21.04.2

widgets/open-tickets/configs.xml
update widget version to 20.10.3
=> chore(install): update widget version to 20.10.3

Jenkinsfile
enable el8 build and packaging develop
=> enable el8 build and packaging develop

Jenkinsfile
enable el8 build and packaging master
=> enable el8 build and packaging master

Jenkinsfile
enable el8 build and packaging dev-21.04.x
=> enable el8 build and packaging dev-21.04.x

Jenkinsfile
enable el8 build and packaging dev-20.10.x
=> enable el8 build and packaging dev-20.10.x

Jenkinsfile
enable el8 build and packaging 21.10.x
=> enable el8 build and packaging 21.10.x

Jenkinsfile
enable el8 build and packaging 21.04.x
=> enable el8 build and packaging 21.04.x

Jenkinsfile
enable el8 build and packaging 20.10.x
=> enable el8 build and packaging 20.10.x

Jenkinsfile
enable el8 build and packaging dev-21.10.x
=> enable el8 build and packaging dev-21.10.x

www/modules/centreon-open-tickets/providers/Mail/MailProvider.class.php, www/modules/centreon-open-tickets/providers/Mail/library/Exception.php
continue a previous commit: https://github.com/centreon/centreon-open-tickets/pull/206
Previous commit: https://github.com/centreon/centreon-open-tickets/pull/206
=> enh(provider): manage phpmailer exception

Jenkinsfile
Please include a short resume of the changes and what is the purpose of PR. Any relevant information should be added to help:
* **QA Team** (Quality Assurance) with tests.
* **reviewers** to understand what are the stakes of the pull request.
=> fix(build): Fix checkout centron build method Jenkinsfile

www/modules/centreon-open-tickets/conf.php
Please include a short resume of the changes and what is the purpose of PR. Any relevant information should be added to help:
* **QA Team** (Quality Assurance) with tests.
* **reviewers** to understand what are the stakes of the pull request.
=> chore(install): update version to 22.04.0-beta.2

Jenkinsfile, ci/debian/control, ci/debian/rules, ci/debian/substvars, ci/scripts/centreon-deb-package.sh
Please include a short resume of the changes and what is the purpose of PR. Any relevant information should be added to help:
* **QA Team** (Quality Assurance) with tests.
* **reviewers** to understand what are the stakes of the pull request.
=> Normalize VERSION variable to Debian format
